apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: exareme-master-volume
    type: local
  name: exareme-master-volume
spec:
  storageClassName: rook-ceph-block
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/lsmyrnaios/exareme/data/"
