version: '3'

services:
  exareme:
    image: ${EXAREME_IMAGE}
    environment:
      - CONSULURL=${EXAREME_KEYSTORE}
      - NODE_NAME=${FEDERATION_NODE}
      - FEDERATION_ROLE=${FEDERATION_ROLE}
      - TEMP_FILES_CLEANUP_TIME=30
      - NODE_COMMUNICATION_TIMEOUT=30000        # (MILIS) NODE COMMUNICATION WILL DROP IF TIMEOUT IS PASSED
      - ENVIRONMENT_TYPE=PROD                   # TEST / DEV / PROD
#    depends_on:
#      - exareme-keystore
#      - exareme-master
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.role == worker # Ensures we only start on worker nodes
          - node.labels.name == ${FEDERATION_NODE}
    volumes:
      - ${LOCAL_DATA_FOLDER}:${DOCKER_DATA_FOLDER}
