version: '3.2'

services:
  exareme-keystore:
    image: bitnami/consul:1.8.4
    ports:         # Used for Debugging
      - target: 8500
        published: 8500
        protocol: tcp
        mode: host
    environment:
      - CONSUL_BIND_INTERFACE=lo
    deploy:
      placement:
        constraints:
          - node.labels.role == master       # Ensures we only start on master nodes
          - node.labels.name == ${FEDERATION_NODE}

  exareme-master:
    image: ${EXAREME_IMAGE}
    environment:
      - CONSULURL=${EXAREME_KEYSTORE}
      - NODE_NAME=${FEDERATION_NODE}
      - FEDERATION_ROLE=${FEDERATION_ROLE}
      - TEMP_FILES_CLEANUP_TIME=30
      - NODE_COMMUNICATION_TIMEOUT=30000        # (MILIS) NODE COMMUNICATION WILL DROP IF TIMEOUT IS PASSED
      - ENVIRONMENT_TYPE=PROD                   # TEST / DEV / PROD
      - LOG_LEVEL=DEBUG                          # INFO / DEBUG
      - CONVERT_CSVS=TRUE                       # TRUE / FALSE
    depends_on:
      - exareme-keystore
    deploy:
      placement:
        constraints:
          - node.labels.role == master # Ensures we only start on master nodes
          - node.labels.name == ${FEDERATION_NODE}
    ports:
      - target: 9090     # So that we can access the Exareme REST API / interface
        published: 9090
        protocol: tcp
        mode: host
    volumes:
      - ${LOCAL_DATA_FOLDER}:${DOCKER_DATA_FOLDER}
