- name: Run Exareme Worker
  shell: >
    echo {{master_become_pass}} | sudo -S
    env FEDERATION_NODE={{ hostvars[my_host]['hostname'] }}
    EXAREME_IMAGE={{ EXAREME_IMAGE }}:{{ EXAREME_TAG }} EXAREME_KEYSTORE={{ EXAREME_KEYSTORE }}
    DOCKER_DATA_FOLDER={{ DOCKER_DATA_FOLDER }} LOCAL_DATA_FOLDER={{ hostvars[my_host]['data_path'] }}
    kompose convert -f ../Kompose-Files/docker-kompose-worker.yml
    && sudo kubectl create -f exareme-persistentvolume-custom.yaml
    && sudo kubectl create -f exareme-claim0-persistentvolumeclaim-custom.yaml
    && sudo kubectl create -f exareme-pod.yaml
    && sudo kubectl create -f exareme-service-custom.yaml
  args:
    chdir: "{{ home_path }}KubeFiles/"
  environment:
    FEDERATION_NODE: "{{ hostvars[my_host]['hostname'] }}"
    EXAREME_IMAGE: "{{ EXAREME_IMAGE }}:{{ EXAREME_TAG }}"
    EXAREME_KEYSTORE: "{{ EXAREME_KEYSTORE }}"
    DOCKER_DATA_FOLDER: "{{ DOCKER_DATA_FOLDER }}"
    LOCAL_DATA_FOLDER: "{{ hostvars[my_host]['data_path'] }}"
