- name: Run Exareme Worker
  shell: >
    env FEDERATION_NODE={{ hostvars[my_host]['hostname'] }} FEDERATION_ROLE=worker
    EXAREME_IMAGE={{ EXAREME_IMAGE }}:{{ EXAREME_TAG }} EXAREME_KEYSTORE={{ EXAREME_KEYSTORE }}
    DOCKER_DATA_FOLDER="{{ DOCKER_DATA_FOLDER }}" LOCAL_DATA_FOLDER="{{ hostvars[my_host]['data_path'] }}"
    kompose convert -f ../../Kompose-Files/docker-kompose-worker.yml
    && python createWorkerResources.py ${FEDERATION_NODE}
    && cat ${FEDERATION_NODE}/exareme-${FEDERATION_NODE}-persistentvolume-custom.yaml | sed "s|<data_path>|${LOCAL_DATA_FOLDER}|" | kubectl create -f -
    && kubectl create -f ${FEDERATION_NODE}/exareme-${FEDERATION_NODE}-claim0-persistentvolumeclaim-custom.yaml
    && kubectl create -f ${FEDERATION_NODE}/exareme-${FEDERATION_NODE}-deployment.yaml
    && kubectl create -f ${FEDERATION_NODE}/exareme-${FEDERATION_NODE}-service-custom.yaml
    && systemctl restart firewalld
  args:
    chdir: "{{ home_path }}Resources/workers"
  environment:
    FEDERATION_NODE: "{{ hostvars[my_host]['hostname'] }}"
    FEDERATION_ROLE: "worker"
    EXAREME_IMAGE: "{{ EXAREME_IMAGE }}:{{ EXAREME_TAG }}"
    EXAREME_KEYSTORE: "{{ EXAREME_KEYSTORE }}"
    DOCKER_DATA_FOLDER: "{{ DOCKER_DATA_FOLDER }}"
    LOCAL_DATA_FOLDER: "{{ hostvars[my_host]['data_path'] }}"
