---
- name: Get Hostname For Worker Nodes
  shell: echo {{master_become_pass}} | sudo -S kubectl get nodes -o json | jq --raw-output '.items[] | select(.metadata.labels."node-role.kubernetes.io\/master"==null) | .metadata.name'
  # We use "--raw-output" here as we want to have multiple worker-names, each in a separate line.
  register: workerHostNames

- name:  Add Labels To Worker Node
  shell: >
    echo {{master_become_pass}} | sudo -S bash -c
    'kubectl label nodes {{ item }} name={{ item }} --overwrite
    && kubectl label nodes {{ item }} role=worker --overwrite
    && kubectl label nodes {{ item }} node-role.kubernetes.io/worker= --overwrite'
  with_items:
   - "{{ workerHostNames.stdout_lines }}"
