---
- name: Get Hostname For Master Node # We haven't add any labels to this point
  shell: kubectl get nodes -o json | jq --join-output '.items[] | select(.metadata.labels."node-role.kubernetes.io\/master") | .metadata.name'
  # We use "--join-output" here as we want to have a single hostname without a "\n" in the end.
  register: hostName

- name:  Add Label Name To Master Node
  shell: >
    kubectl label nodes {{ hostName.stdout }} name={{ hostName.stdout }} --overwrite
    && kubectl label nodes {{ hostName.stdout }} role=master --overwrite
