---
- name: Stop Exareme Spesific Worker
  shell: >
    env FEDERATION_NODE={{ my_name }} FEDERATION_ROLE=worker
    EXAREME_IMAGE={{ EXAREME_IMAGE }}:{{ EXAREME_TAG }} EXAREME_KEYSTORE={{ EXAREME_KEYSTORE }}
    DOCKER_DATA_FOLDER="{{ DOCKER_DATA_FOLDER }}" LOCAL_DATA_FOLDER="{{ hostvars[my_host]['data_path'] }}"
    kompose down -f docker-kompose-worker.yml
  args:
    chdir: "{{ home_path }}Kompose-Files/"


# TODO - Remove custom resources also... all resources containing the worker's hostname..!

# Don't know if it' usefull.. and it's not yet stable..
#name: Drain worker node
#  shell: >
#    kubectl drain {{ hostvars[my_host]['hostname'] }} --delete-local-data --force --ignore-daemonsets
#    && echo {{master_become_pass}} | sudo -S  kubectl uncordon {{ leader.stdout }}
#  tags:
#    - exareme
