---
- name: Stop Exareme Spesific Worker
  shell: >
    echo {{master_become_pass}} | sudo -S
    env FEDERATION_NODE={{ my_name }}
    EXAREME_IMAGE={{ EXAREME_IMAGE }}:{{ EXAREME_TAG }} EXAREME_KEYSTORE={{ EXAREME_KEYSTORE }}
    DOCKER_DATA_FOLDER="{{ DOCKER_DATA_FOLDER }}" LOCAL_DATA_FOLDER="{{ hostvars[my_host]['data_path'] }}"
    kompose down -f docker-kompose-worker.yml
  args:
    chdir: "{{ home_path }}Kompose-Files/"
