version: '3.2'

#networks:
#  net-federation:
#    external:
#      name: mip-federation

services:
  exareme-keystore:
    image: progrium/consul
    command:
      - -server
      - -bootstrap
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.role == master       # Ensures we only start on master nodes
          - node.labels.name == ${FEDERATION_NODE}
#    networks:
#      - "net-federation"
    ports:
      - "8500:8500"

  exareme-master:
    image: ${EXAREME_IMAGE}
    environment:
      - CONSULURL=${EXAREME_KEYSTORE}
      - NODE_NAME=${FEDERATION_NODE}
      - FEDERATION_ROLE=${FEDERATION_ROLE}
      - TEMP_FILES_CLEANUP_TIME=30
      - NODE_COMMUNICATION_TIMEOUT=30000        # (MILIS) NODE COMMUNICATION WILL DROP IF TIMEOUT IS PASSED
      - ENVIRONMENT_TYPE=PROD                   # TEST / DEV / PROD
    depends_on:
      - exareme-keystore
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.role == master # Ensures we only start on master nodes
          - node.labels.name == ${FEDERATION_NODE}
    ports:
      - target: 9090     # So that we can access the Exareme REST API / interface
        published: 9090
        protocol: tcp
        mode: host
#    networks:
#      - "net-federation"
    volumes:
      - ${LOCAL_DATA_FOLDER}:${DOCKER_DATA_FOLDER}
