---

# TODO - Instruct the master to do a "kompose down" for the worker-docker-compose-file and other worker's resources.


- name: Delete node from kubernetes-cluster
  # The worker cannot set itself out of kubernetes.. only the master can do it for it.. (?)
  shell: kubectl drain {{ my_name }} --force ; kubectl delete node {{ my_name }} --force
  ignore_errors: true
